const ADD_COMMENT = 'ADD_COMMENT';
const REMOVE_COMMENT = 'REMOVE_COMMENT';
const EDIT_COMMENT = 'EDIT_COMMENT';
const INCREMENT_COMMENT = 'INCREMENT_COMMENT';
const DECREMENT_COMMENT = 'DECREMENT_COMMENT';